events {}

http {
    server {
        listen 80;
        server_name
	    nguyeanhxuan2712.com
            api.nguyenanhxuan2712.com
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name nguyenanhxuan2712.com;
        ssl_certificate     /etc/nginx/ssl/origin.crt;
        ssl_certificate_key /etc/nginx/ssl/origin.key;
        location / {
            proxy_pass http://frontend:3000;
        }
    }

    server {
        listen 443 ssl;
        server_name api.nguyenanhxuan2712.com;
        ssl_certificate     /etc/nginx/ssl/origin.crt;
        ssl_certificate_key /etc/nginx/ssl/origin.key;
        location / {
            proxy_pass http://backend:8080;
        }
    }
}
